In [9]:
# create a random array using dask array
import dask.array as da

# using arrange to create an array with values from 0 to 10
x = da.arange(11,chunks=5)
x.compute()

#array([0,1,2,3,4,5,6,7,8,9])

# to see size of each chunk
x.chunks
#o/p ((5,5,1),)

((5, 5, 1),)

In [24]:
import dask.array as da

# using arrange to create an array with values from 0 to 10
x = da.arange(11,chunks=5)
numpyArr1 = x.compute()

# to see size of each chunk
x.chunks

for num in numpyArr1:
    print(num)
print(numpyArr1[1::])
print(numpyArr1[::])
print(numpyArr1[1::4])



0
1
2
3
4
5
6
7
8
9
10
[ 1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[1 5 9]


In [31]:
# converting an numpy array into a dask array
import numpy as np
import dask.array as da

arr1 = np.arange(10)
print(arr1) # numpy array

daskArr1 = da.from_array(arr1, chunks=4)
daskArr1.compute() #results in a dask array

daskArr1.chunks



[0 1 2 3 4 5 6 7 8 9]


((4, 4, 2),)

In [36]:
# converting an numpy array into a dask array
import numpy as np
import dask.array as da

arr1 = np.arange(10)
print(arr1) # numpy array

daskArr1 = da.from_array(arr1, chunks=4)
daskArr1.compute() #results in a dask array
print(type(daskArr1)) # type of array it shows
type(daskArr1) # type of array it shows

daskArr1 # structure is displaying

[0 1 2 3 4 5 6 7 8 9]
<class 'dask.array.core.Array'>


dask.array<array, shape=(10,), dtype=int32, chunksize=(4,), chunktype=numpy.ndarray>

In [37]:
import numpy as np
import dask.array as da

arr1 = np.arange(10)
print(arr1) # numpy array

daskArr1 = da.from_array(arr1, chunks=4)
# num1 = daskArr1.mean(axis=0)
daskArr1.compute()

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
import numpy as np
import dask.array as da
import time

numpyArr1 = np.arange(100000)#numpy array
daskArr1 = da.from_array(numpyArr1, chunks=100)
%time
daskArr1.compute()
daskArr1.mean().compute() #computing mean of the array
daskArr1.sum().compute()# compute sum of the array

numpyArr2 = np.arange(100000)
numpyArr2.mean()

Wall time: 0 ns


49999.5

In [69]:
import dask.array as da
a = da.random.random((10000,10000), chunks=(1000,1000))
a.compute()

array([[0.97332584, 0.33056398, 0.82342844, ..., 0.50564527, 0.91859559,
        0.38411515],
       [0.05326062, 0.95235244, 0.69259102, ..., 0.39776141, 0.16602577,
        0.50974776],
       [0.66522184, 0.89290783, 0.25096811, ..., 0.97219992, 0.84298489,
        0.35254929],
       ...,
       [0.27962231, 0.20260828, 0.79079582, ..., 0.69364329, 0.42834668,
        0.89295855],
       [0.01848156, 0.66085659, 0.65967106, ..., 0.77665136, 0.28297131,
        0.07878013],
       [0.13792262, 0.47070594, 0.12597544, ..., 0.28207489, 0.86663509,
        0.48416569]])

In [38]:
import pandas
import dask.dataframe as daskDataFrame
person_IDs = [1,2,3,4,5,6,7,8,9]
person_first_names = ['ashwini','ramya','akhil','arun','abhi','rakesh','raju','sriram','sruthi']
person_last_names = ['yanagandul','bingi','donthi','akula','adupa','junna','vemula','surarapu','kongara']
person_DOBs = ['1999-12-26','2005-12-17','2020-12-1','2007-2-3','1999-1-6','1997-2-5','1997-2-19','1996-2-16','1995-2-17']
peoplePandasDataFrame = pandas.DataFrame({'Person Id':person_IDs,'First_Names':person_first_names,'Last_Names':person_last_names,'Person_DOBs':person_DOBs},columns=['Person Id','First_Names','Last_Names','Person_DOBs'])
#print(peoplePandasDataFrame)# print pandas dataframe

# converts the pandas dataframe to dask dataframe
peopleDaskDataFrame = daskDataFrame.from_pandas(peoplePandasDataFrame,npartitions=2)
#print(peopleDaskDataFrame) # print the converted pandas dataframe to dask dataframe

#shows the bounderies of the partitioning scheme,produces the output(0,5,9)
print(peopleDaskDataFrame.divisions)

#shows how many partitions exist in the DataFrame,produces the output :2,
#partition 1 holds 0 to 4 ,partition 2 holds 5 to 8
print(peopleDaskDataFrame.npartitions)

(0, 5, 8)
2


In [39]:
#counts the number of rows in each partition
peopleDaskDataFrame.map_partitions(len).compute() 
print(peopleDaskDataFrame)

Dask DataFrame Structure:
              Person Id First_Names Last_Names Person_DOBs
npartitions=2                                             
0                 int64      object     object      object
5                   ...         ...        ...         ...
8                   ...         ...        ...         ...
Dask Name: from_pandas, 2 tasks


In [23]:
#filter out people with a last name of     and recount the rows
people_filtered = peopleDaskDataFrame[peopleDaskDataFrame['Last_Names']!= 'kongara']# == we can give it display the only kongara last name count
print(people_filtered.map_partitions(len).compute())

#collapses the two partitions into one
people_filtered_reduced = people_filtered.repartition(npartitions=1)
print(people_filtered_reduced.map_partitions(len).compute())



0    5
1    3
dtype: int64
0    8
dtype: int64


In [1]:
# client -->submit the task to shedulers
#shedulers -->will asign thesse tasks to workers
# workes --> will execute the task

from dask.distributed import Client
client = Client()
print(client)




<Client: 'tcp://127.0.0.1:60715' processes=4 threads=4, memory=4.21 GB>


In [2]:
# another way to do
from distributed import Client
client = Client(n_workers=4,threads_per_worker=4)
client

C:\Users\LENOVO\anaconda3\lib\site-packages\distributed\node.py:151: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 60761 instead
  warnings.warn(


<Client: 'tcp://127.0.0.1:60764' processes=4 threads=16, memory=4.21 GB>

In [30]:
import time
from distributed import Client,LocalCluster

def hard():
    time.sleep(5)
    return 'Hard'
def easy():
    time.sleep(2)
    return 'Easy'
cluster = LocalCluster()
client = Client(cluster)
future = client.submit(easy)#submit executes the function and return a future object
#print(future)
print(future.result()) # results() blocks until task completes and data arrives

future1 = client.submit(hard)# submit executes the function and return the hard
#print(future1) # its not display the output hard
print(future1.result())# result() is display the output hard



C:\Users\LENOVO\anaconda3\lib\site-packages\distributed\node.py:151: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 61045 instead
  warnings.warn(


Easy
<Future: pending, key: hard-c6db839e27c82418a9d9476d919a7fa2>


In [18]:
%%time
def square(x):
    time.sleep(1)
    return x*x

x_sq = square(2)
y_sq = square(4)

res = x_sq + y_sq
res   

Wall time: 2 s


20

In [31]:
%%time
from dask import delayed

x_sq = delayed(square(2)) # delayed(square)(2)
y_sq = delayed(square(4)) #delayed(square)(4)

res = x_sq + y_sq
res  # if we didnt give compute it doesn't display addition
#%time res.compute()# compute() it gives output


Wall time: 2.19 s


Delayed('add-a336c5eee671ba6cee7243fa44f7cefa')

In [24]:
#!pip install graphviz
#res.visualize() # graphical representation

In [42]:
%%time
def square(x):
    time.sleep(1)# sleep for 1 sec
    return x*x

def power_3(x):
    time.sleep(2)
    return x*x*x

final_list = []
for i in range(1,11):
    if i%2 == 0:
        final_list.append(square(i))
    else:
        final_list.append(power_3(i))
        
res = sum(final_list)
res

Wall time: 15.7 s


1445

In [52]:
%%time
@delayed #  using delayed decorator
def square(x):
    #time.sleep(1)# sleep for 1 sec
    return x*x

@delayed
def power_3(x):
    #time.sleep(1)
    return x*x*x

final_list = []
for i in range(1,11):
    if i%2 == 0:
        final_list.append(square(i))
    else:
        final_list.append(power_3(i))
        
res = delayed(sum)(final_list)
res
%time res.compute()

Wall time: 20.5 s
Wall time: 20.6 s


1445